version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: make test
  lint:
    docker:
    - image: cimg/go:1.20.0
    steps:
    - checkout
    - run: make lint
workflows:
  version: 2
  build_and_lint:
    jobs:
    - build
    - lint
